name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install cunit
      run: sudo apt-get install libcunit1-dev libcunit1-doc libcunit1
    - name: make
      run: make
    - name: make tests
      run: cd tests && make
    - name: run tests
      run: ./main
